FROM hseeberger/scala-sbt:8u312_1.6.2_2.13.8 as builder
WORKDIR /src

# Cache dependencies first
COPY src/ .

RUN sbt update
# Then build
COPY . .
RUN  sbt compile clean package

FROM openjdk:8-jre-alpine3.9 
WORKDIR /srv
COPY --from=builder /src/target/scala-2.13/helloworld_2.13-1.0.jar app.jar
COPY --from=builder /usr/share/scala/lib/scala-library.jar ./scala-library.jar

CMD ["java",  "-cp", "app.jar:scala-library.jar", "Hello"]