spring: 
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_DBNAME:employee_db}?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:toor}
  jpa: 
    properties: 
      hibernate: 
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: ${DB_MIGRATIONS:update}

server: 
  port: ${HTTP_PORT:8081}


